### ISSUE TITLE
Script hook v dot net not working with any mods, keep getting error mesages

### ISSUE THREAD

**Issue by peoplethatprint** [scripthookvdotnet/scripthookvdotnet#1083]
**Version**
3.4.0

**Description**
Script hook v dot net is not working with any of the mods I have that require it. The log loads perfectly in game and I can reload when the key is pressed but the mods still don't work and I get the error messages from below.  If needed I can get screen shots of the errors popping up in game. Below is the messages from the log:

[23:05:04] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[23:05:04] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[23:05:04] [DEBUG] Loading scripts from E:\Epic Games\GTAV\scripts ...
[23:05:04] [DEBUG] Loading assembly iFruitAddon2.dll ...
[23:05:04] [INFO] Found 1 script(s) in iFruitAddon2.dll resolved to API 2.11.3.
[23:05:04] [DEBUG] Loading assembly Lively World.dll ...
[23:05:04] [INFO] Found 1 script(s) in Lively World.dll resolved to API 2.11.3.
[23:05:04] [DEBUG] Loading assembly LSlife.dll ...
[23:05:05] [INFO] Found 1 script(s) in LSlife.dll resolved to API 2.11.3.
[23:05:05] [DEBUG] Loading assembly NativeUI.dll ...
[23:05:05] [INFO] Found 1 script(s) in NativeUI.dll resolved to API 2.11.3.
[23:05:05] [DEBUG] Loading assembly PullMeOver.dll ...
[23:05:05] [INFO] Found 2 script(s) in PullMeOver.dll resolved to API 2.11.3.
[23:05:05] [DEBUG] Loading assembly RealParamedics.dll ...
[23:05:05] [WARNING] Resolving API version 0.0.0.
[23:05:05] [INFO] Found 1 script(s) in RealParamedics.dll resolved to API 2.11.3.
[23:05:05] [DEBUG] Instantiating script iFruitAddon2.iFruitAddon2 ...
[23:05:05] [INFO] Started script iFruitAddon2.iFruitAddon2.
[23:05:05] [DEBUG] Instantiating script LivelyWorld ...
[23:05:06] [ERROR] Failed to instantiate script LivelyWorld because constructor threw an exception: System.TypeInitializationException: The type initializer for 'LivelyWorld' threw an exception. ---> System.MissingMethodException: Method not found: 'UInt64* SHVDN.NativeFunc.Invoke(UInt64, UInt64*, Int32)'.
   at GTA.Native.Function.Call(Hash hash, InputArgument argument0, InputArgument argument1)
   at GTA.World.AddRelationshipGroup(String groupName)
   at LivelyWorld..cctor()
   --- End of inner exception stack trace ---
   at LivelyWorld..ctor()
[23:05:06] [DEBUG] Instantiating script LSlife.LSL ...
[23:05:06] [ERROR] Failed to instantiate script LSlife.LSL because constructor threw an exception: System.MissingMethodException: Method not found: 'UInt64* SHVDN.NativeFunc.Invoke(UInt64, UInt64*, Int32)'.
   at GTA.Native.Function.Call[T](Hash hash, InputArgument argument0)
   at LSlife.LSL.Setup() in C:\Users\Mcal\source\repos\LSLife\LSlife\Main.cs:line 417
   at LSlife.LSL..ctor() in C:\Users\Mcal\source\repos\LSLife\LSlife\Main.cs:line 403
[23:05:06] [DEBUG] Instantiating script NativeUI.BigMessageThread ...
[23:05:06] [INFO] Started script NativeUI.BigMessageThread.
[23:05:06] [DEBUG] Instantiating script PullMeOver.PullMeOverMain ...
[23:05:06] [INFO] Started script PullMeOver.PullMeOverMain.
[23:05:06] [DEBUG] Instantiating script PullMeOver.SpeedDisplay ...
[23:05:06] [ERROR] Failed to instantiate script PullMeOver.SpeedDisplay because constructor threw an exception: System.MissingMethodException: Method not found: 'UInt64* SHVDN.NativeFunc.Invoke(UInt64, UInt64*, Int32)'.
   at GTA.Native.Function.Call[T](Hash hash, InputArgument argument0)
   at GTA.Scaleform..ctor(String scaleformID)
   at NativeUI.UIMenu..ctor(String title, String subtitle, Point offset, String spriteLibrary, String spriteName)
   at NativeUI.UIMenu..ctor(String title, String subtitle)
   at PullMeOver.SpeedDisplay.SetDisplay() in C:\Users\Josh\code\GTAV\pullmeover\pullmeover\SpeedDisplay.cs:line 105
   at PullMeOver.SpeedDisplay..ctor() in C:\Users\Josh\code\GTAV\pullmeover\pullmeover\SpeedDisplay.cs:line 76
[23:05:06] [DEBUG] Instantiating script Main ...
[23:05:06] [ERROR] Failed to instantiate script Main because constructor threw an exception: System.MissingMethodException: Method not found: 'UInt64* SHVDN.NativeFunc.Invoke(UInt64, UInt64*, Int32)'.
   at GTA.Native.Function.Call(Hash hash, InputArgument[] arguments)
   at Main..ctor()
[23:05:06] [ERROR] Caught fatal unhandled exception:
System.MissingMethodException: Method not found: 'UInt64* SHVDN.NativeFunc.Invoke(UInt64, UInt64*, Int32)'.
   at GTA.Native.Function.Call[T](Hash hash)
   at iFruitAddon2.iFruitAddon2.Initialize(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()
[23:05:06] [ERROR] The exception was thrown while executing the script iFruitAddon2.iFruitAddon2.
[23:05:06] [WARNING] Aborted script iFruitAddon2.iFruitAddon2.
[23:05:06] [ERROR] Caught fatal unhandled exception:
System.MissingMethodException: Method not found: 'UInt64* SHVDN.NativeFunc.Invoke(UInt64, UInt64*, Int32)'.
   at GTA.Native.Function.Call[T](Hash hash)
   at GTA.Game.get_Player()
   at PullMeOver.PullMeOverMain.TrackVehicle() in C:\Users\Josh\code\GTAV\pullmeover\pullmeover\PullMeOver2.cs:line 1057
   at PullMeOver.PullMeOverMain.TrackPlayer() in C:\Users\Josh\code\GTAV\pullmeover\pullmeover\PullMeOver2.cs:line 1189
   at PullMeOver.PullMeOverMain.OnTick(Object sender, EventArgs e) in C:\Users\Josh\code\GTAV\pullmeover\pullmeover\PullMeOver2.cs:line 195
   at SHVDN.Script.MainLoop()
[23:05:06] [ERROR] The exception was thrown while executing the script PullMeOver.PullMeOverMain.
[23:05:06] [ERROR] Caught fatal unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at PullMeOver.PullMeOverMain.EndEvent(Boolean change) in C:\Users\Josh\code\GTAV\pullmeover\pullmeover\PullMeOver2.cs:line 1012
   at PullMeOver.PullMeOverMain.OnAborted(Object sender, EventArgs e) in C:\Users\Josh\code\GTAV\pullmeover\pullmeover\PullMeOver2.cs:line 301
   at SHVDN.Script.Abort()
[23:05:06] [ERROR] The exception was thrown while executing the script PullMeOver.PullMeOverMain.
[23:05:06] [WARNING] Aborted script PullMeOver.PullMeOverMain.

**Comment by peoplethatprint** [comment]
Problem has been fixed by going into properties of each mod zip file and clicking unblock and then putting them into scripts folder again.

**Comment by chpff** [comment]
can you explain how can I unblock zip files pls

> Problem has been fixed by going into properties of each mod zip file and clicking unblock and then putting them into scripts folder again.

**Comment by kagikn** [comment]
@chpff you could go to Disucussions and post your question there, not I'm not answering it here
