### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by sonny-dev** [scripthookvdotnet/scripthookvdotnet#1390]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### SHVDN Version

200388b

### Game Version

v1.0.3095.0

### Bug Description

This error pertains to ARS (Auto Sport Racing System), but seems to be related to Vehicle SetBrakes. 
This happens when loading a Track and the Drivers for the Race. 
I believe the error is due to the latest version of the game (3095) messing with some Vehicle Hash stuff... 

```
[ERROR] Caught unhandled exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at ARS.ARS.SetBrakes(Vehicle handle, Single value)
   at ARS.Racer..ctor(Vehicle RacerCar, Ped RacerPed)
   at ARS.ARS.LoadGrid(String dlist, Int32 maxcars)
   at ARS.ARS.HandleMenu()
   at ARS.ARS.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.DoTick()
[08:53:05] [ERROR] The exception was thrown while executing the script ARS.ARS from "C:\Program Files\Rockstar Games\Grand Theft Auto V\scripts\ARS\ARS.dll".
[08:53:05] [WARNING] Aborted script ARS.ARS.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
   at SHVDN.Script.Abort()
   at SHVDN.Script.DoTick()
   at SHVDN.Script.MainLoop()
```

### Steps To Reproduce

Using ARS script, load a race. 
As the Drivers are being loaded, the script will crash due to being unable to set the vehicles Brakes. 

### The Current Behavior

Scripthookvdotnet is unable to provide the SetBrakes on Vehicles. 

### The Expected Behavior

Should be able to retrieve "SetBrakes"

**Comment by nomakewan** [comment]
This is a bug with ARS, not SHVDN. Vehicle.SetBrakes() is an ARS function: https://github.com/Eddlm/autosport-racing-system-gta/blob/master/NewRacingSystem/AutosportRacingSystem.cs#L573

I would recommend opening an issue on ARS's github instead.

**Comment by kagikn** [comment]
SHVDN is not responsible to this issue. `ARS.ARS.SetBrakes()` in ARS fails to find the address to extract with the memory pattern `74 0A F3 0F 11 B3 ? ? ? ? EB 25` and tries to dereference the null pointer in b3095.

Also, type concise titles to explain what the issues are like when you create issues, to people can search for relevant issues.
