### ISSUE TITLE
[Bug]: LockRecursionException

### ISSUE THREAD

**Issue by tp-mods** [scripthookvdotnet/scripthookvdotnet#1466]
### What modules are you seeing the problem on?

ScriptHookVDotNet.asi (runtime)

### SHVDN Version

ddae3ca

### Game Version

v1.0.3285.0

### Bug Description

One of my scripts is occasionally crashing due to a conflict with another script. It happens when each script tries to run two specific natives at the same time (possible race condition?) . One native is REPORT_POLICE_SPOTTED_PLAYER and other is GET_BLIP_SPRITE. These two do completely different things and yet somehow they throw a LockRecursionException. This problem didn't happen on the non-nightly version of SHVDN 3.6.0.
Here is the stacktrace for the exception:

System.Threading.LockRecursionException: Recursive read lock acquisitions not allowed in this mode.
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout)
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLock(TimeoutTracker timeout)
   at SHVDN.ScriptDomain.ExecuteTaskWithGameThreadTlsContext(IScriptTask task)
   at SHVDN.NativeFunc.Invoke(UInt64 hash, UInt64* argPtr, Int32 argCount)
   at GTA.Native.Function.Call[T](Hash hash, InputArgument argument)
   at PoliceBehaviour.BlipManager.FlashBlip(BlippedEntity blipData, Int64 dt)
   at PoliceBehaviour.BlipManager.FlashBlips()
   at SHVDN.NativeFunc.NativeCall()
   at SHVDN.NativeFunc.InvokeInternal(UInt64 hash, UInt64* argPtr, Int32 argCount)
   at SHVDN.NativeFunc.NativeTaskPtrArgs.Run()
   at SHVDN.ScriptDomain.ExecuteTaskWithGameThreadTlsContext(IScriptTask task)
   at SHVDN.NativeFunc.Invoke(UInt64 hash, UInt64* argPtr, Int32 argCount)
   at GTA.Native.Function.Call(Hash hash, InputArgument[] arguments)
   at NativeCaller.Call(Hash hash, InputArgument[] inputargs)
   at PoliceDogAI.Main.UpdatePlayerLastSeenLocation(Ped dog, Boolean seenFromDog, Boolean dogSittingInVehicle, Ped owner, Boolean ownerInCombat)
   at PoliceDogAI.Main.EvaluateTarget(Ped dog, Vector3 dogPosition, Ped owner)
   at PoliceDogAI.Main.UpdateDogAI(Ped dog, Ped owner)
   at PoliceDogAI.Main.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.DoTick()

### Steps To Reproduce

1. Run two script threads.
2. Have one of them run REPORT_POLICE_SPOTTED_PLAYER and the other GET_BLIP_SPRITE.
3. Wait to have both of them run in the same frame.
4. Script crash.

### The Current Behavior

Script crashes when calling REPORT_POLICE_SPOTTED_PLAYER and GET_BLIP_SPRITE in the same frame by two different scripts. 

### The Expected Behavior

Script shouldn't crash when calling these two.

**Comment by kagikn** [comment]
```
at PoliceBehaviour.BlipManager.FlashBlips()
at SHVDN.NativeFunc.NativeCall()
```
That is sus part of the stack trace you reported. `NativeFunc.NativeCall` just calls SHV's `nativeCall` but the stacktrace says there's more inner managed calls in `NativeFunc.NativeCall`, which is not supposed to happen. Can I see subsets of your `PoliceDogAI` and `PoliceBehaviour` so I can guess the causes more accurately?

**Comment by tp-mods** [comment]
This is the part from `PoliceDogAI` :

`
private void UpdatePlayerLastSeenLocation(Ped dog, bool seenFromDog, bool dogSittingInVehicle, Ped owner = null, bool ownerInCombat = false)
{
    TaskState dogTask = dogInfoList[dog.Handle].Task;
    if (seenFromDog || dogTask == TaskState.TauntingPlayer)
    {
        // If the player is seen, update the timer after which the player can be considered lost.
        dogInfoList[dog.Handle].GameTimeBeforeCanIgnoreTargetNotSeen = gameTime + targetNotSeenIgnoreTime * 1000;
    }

    if (gameTime <= dogInfoList[dog.Handle].GameTimeBeforeCanIgnoreTargetNotSeen)
    {
        // If the dog has recently seen the player, update last seen position.
        dogInfoList[dog.Handle].PlayerLastSeenLocation = playerPosition;

        // If the dog has recently entered a vehicle, keep updating this for a little while.
        if (gameTime <= dogInfoList[dog.Handle].GameTimeBeforeCanLeaveVehicleForSearch || !dogSittingInVehicle)
        {
            if (seenFromDog)
            {
                if (DoesTaskRequireBlockOfPermanentEvents(dogTask))
                {
                    // If the dog is blocking permanent events, he won't automatically communicate the player's position to his friendlies.
                    // So we need to manually alert either the owner (if alive) or the cop cached.
                    Ped alertCop = owner ?? copToAlert;
                    bool alertCopInCombat = owner != null ? ownerInCombat : copToAlertInCombat;

                    if (alertCop != null)
                    {
                        if (alertCopInCombat)
                        {
                            // Register the threat again to reset the internal "target lost" timer of this ped.
                            NativeCaller.Call(Hash.REGISTER_TARGET, alertCop.Handle, playerPed.Handle);
                        }
                        else
                        {
                            // Reassign the combat task.
                            int combatFlags = playerWantedLvl == 1 ? 65536 : 0;
                            NativeCaller.Call(Hash.TASK_COMBAT_PED, alertCop.Handle, playerPed.Handle, combatFlags, 0);

                            if (alertCop == copToAlert)
                            {
                                copToAlertInCombat = true;
                            }
                        }
                    }
                }

                // Make the radar flash red and blue and update the last seen position stored by the game.
                Fx.ReportPoliceSpottedPlayer(player);
                // Store the new last seen position.
                playerWantedPosition = player.WantedCenterPosition;
                return;
            }
            // Keep resetting the hidden evasion timer while the dog is still aggro-ing the player.
            NativeCaller.Call(Hash.SUPPRESS_LOSING_WANTED_LEVEL_IF_HIDDEN_THIS_FRAME, player.Handle);
        }
        return;
    }
`

The part from `PoliceBehaviour` is actually from another script not made by me, here is the decompiled code:

`
private void FlashBlip(BlippedEntity blipData, long dt)
{
    if (blipData == null)
    {
        return;
    }

    if (blipData.entity != null && blipData.address != IntPtr.Zero)
    {
        SuppressBlipsForPointer(blipData.address);
    }

    blipData.FlashTime += dt;
    if (blipData.FlashTime <= 500)
    {
        return;
    }

    blipData.FlashTime %= 500L;
    blipData.IsColor2 = !blipData.IsColor2;

    // I assumed it crashes on blip.currentBlip.Sprite since it's the only part where it goes to read stuff
    if (!(blipData.currentBlip == null) && blipData.IsFlashing && !IsSpriteFixedColor(blipData.currentBlip.Sprite))
    {
        Blip currentBlip = blipData.currentBlip;
        if (blipData.IsColor2)
        {
            currentBlip.Color = blipData.Color2;
        }
        else
        {
            currentBlip.Color = blipData.Color1;
        }

        if (!string.IsNullOrEmpty(blipData.blipInfo?.Text))
        {
            currentBlip.Name = blipData.blipInfo.Text;
        }
        else
        {
            currentBlip.Name = "";
        }
    }
}
`

**Comment by tp-mods** [comment]
This is the part from 'PoliceDogAI':

```
private void UpdatePlayerLastSeenLocation(Ped dog, bool seenFromDog, bool dogSittingInVehicle, Ped owner = null, bool ownerInCombat = false)
{
    TaskState dogTask = dogInfoList[dog.Handle].Task;
    if (seenFromDog || dogTask == TaskState.TauntingPlayer)
    {
        // If the player is seen, update the timer after which the player can be considered lost.
        dogInfoList[dog.Handle].GameTimeBeforeCanIgnoreTargetNotSeen = gameTime + targetNotSeenIgnoreTime * 1000;
    }

    if (gameTime <= dogInfoList[dog.Handle].GameTimeBeforeCanIgnoreTargetNotSeen)
    {
        // If the dog has recently seen the player, update last seen position.
        dogInfoList[dog.Handle].PlayerLastSeenLocation = playerPosition;

        // If the dog has recently entered a vehicle, keep updating this for a little while.
        if (gameTime <= dogInfoList[dog.Handle].GameTimeBeforeCanLeaveVehicleForSearch || !dogSittingInVehicle)
        {
            if (seenFromDog)
            {
                if (DoesTaskRequireBlockOfPermanentEvents(dogTask))
                {
                    // If the dog is blocking permanent events, he won't automatically communicate the player's position to his friendlies.
                    // So we need to manually alert either the owner (if alive) or the cop cached.
                    Ped alertCop = owner ?? copToAlert;
                    bool alertCopInCombat = owner != null ? ownerInCombat : copToAlertInCombat;

                    if (alertCop != null)
                    {
                        if (alertCopInCombat)
                        {
                            // Register the threat again to reset the internal "target lost" timer of this ped.
                            NativeCaller.Call(Hash.REGISTER_TARGET, alertCop.Handle, playerPed.Handle);
                        }
                        else
                        {
                            // Reassign the combat task.
                            int combatFlags = playerWantedLvl == 1 ? 65536 : 0;
                            NativeCaller.Call(Hash.TASK_COMBAT_PED, alertCop.Handle, playerPed.Handle, combatFlags, 0);

                            if (alertCop == copToAlert)
                            {
                                copToAlertInCombat = true;
                            }
                        }
                    }
                }

                // Make the radar flash red and blue and update the last seen position stored by the game.
                Fx.ReportPoliceSpottedPlayer(player);
                // Store the new last seen position.
                playerWantedPosition = player.WantedCenterPosition;
                return;
            }
            // Keep resetting the hidden evasion timer while the dog is still aggro-ing the player.
            NativeCaller.Call(Hash.SUPPRESS_LOSING_WANTED_LEVEL_IF_HIDDEN_THIS_FRAME, player.Handle);
        }
        return;
    }

    if (dogInfoList[dog.Handle].PlayerLastSeenLocation != Vector3.Zero)
    {
        // Reset the stored last seen location if the wanted center is closer.
        float distanceFromWantedCenter = playerPosition.DistanceTo(playerWantedPosition);
        float distanceFromLastSeenPosition = playerPosition.DistanceTo(dogInfoList[dog.Handle].PlayerLastSeenLocation);
        if (distanceFromWantedCenter < distanceFromLastSeenPosition)
        {
            dogInfoList[dog.Handle].PlayerLastSeenLocation = Vector3.Zero;
        }
    }
}
```

The part from `PoliceBehaviour` is actually not made my me, here is the decompiled code:

```
private void FlashBlip(BlippedEntity blipData, long dt)
{
    if (blipData == null)
    {
        return;
    }

    if (blipData.entity != null && blipData.address != IntPtr.Zero)
    {
        SuppressBlipsForPointer(blipData.address);
    }

    blipData.FlashTime += dt;
    if (blipData.FlashTime <= 500)
    {
        return;
    }

    blipData.FlashTime %= 500L;
    blipData.IsColor2 = !blipData.IsColor2;
    // I assumed it crashes on blipData.currentBlip.Sprite since it's the only part where it goes to read stuff.
    if (!(blipData.currentBlip == null) && blipData.IsFlashing && !IsSpriteFixedColor(blipData.currentBlip.Sprite))
    {
        Blip currentBlip = blipData.currentBlip;
        if (blipData.IsColor2)
        {
            currentBlip.Color = blipData.Color2;
        }
        else
        {
            currentBlip.Color = blipData.Color1;
        }

        if (!string.IsNullOrEmpty(blipData.blipInfo?.Text))
        {
            currentBlip.Name = blipData.blipInfo.Text;
        }
        else
        {
            currentBlip.Name = "";
        }
    }
}
```

**Comment by tp-mods** [comment]
Hello, I recently did a test with nightly 118 and the issue still persists.

**Comment by kagikn** [comment]
Well, the commit above automatically closed the issue, but I think it should be tested with [nightly.119](https://github.com/scripthookvdotnet/scripthookvdotnet-nightly/releases/tag/v3.6.0-nightly.119) as e219d506b32a2ba9a6676c6eae5d99208a22bff8 fixes a relevant crashing issue. Could you test if the issue still persists with the new build? I would test whether the test still persists if I had an reproducible example myself, but unfortunately I don't have one.

**Comment by tp-mods** [comment]
Alright, I tested my script for around 10 minutes trying to reproduce this and got no crashes. I'd say the issue has been fixed, thanks.
