### ISSUE TITLE
Scripts Broken in 3285 with Nightly Build

### ISSUE THREAD

**Issue by AliciaWindsor** [scripthookvdotnet/scripthookvdotnet#1468]
### What modules are you seeing the problem on?

ScriptHookVDotNet3.dll (v3 SDK/API)

### SHVDN Version

latest nightly build

### Game Version

3285

### Bug Description

All script work in 2372. Created a new environment with 3285 and game crashed. Saw issue on Github so installed the nightly build as recommended. Every single script is now broken. Examples from log, complete list would fill a dozen pages as I have dozens of scripts.

[14:26:33] [ERROR] Failed to instantiate script LemonUI.Menu2.Basics because constructor threw an exception: System.TypeInitializationException: The type initializer for 'LemonUI.Menu2.Basics' threw an exception. ---> System.MissingMethodException: Method not found: 'System.String SHVDN.NativeMemory.PtrToStringUTF8(IntPtr)'.
   at GTA.Native.Function.ObjectFromNative(Type type, UInt64* value)
   at GTA.Native.Function.ReturnValueFromNativeIfNotNull[T](UInt64* result)
   at GTA.Native.Function.Call[T](Hash hash, InputArgument argument0, InputArgument argument1, InputArgument argument2)
   at LemonUI.Scaleform.InstructionalButton..ctor(String description, Control control)
   at LemonUI.Menus.NativeMenu..ctor(String bqnnerText, String name, String description, I2Dimensional banner)
   at LemonUI.Menu2.Basics..cctor()
   --- End of inner exception stack trace ---
   at LemonUI.Menu2.Basics..ctor()
[14:26:33] [ERROR] Failed to instantiate script LemonUI.Menu1.Basics because constructor threw an exception: System.TypeInitializationException: The type initializer for 'LemonUI.Menu1.Basics' threw an exception. ---> System.MissingMethodException: Method not found: 'System.String SHVDN.NativeMemory.PtrToStringUTF8(IntPtr)'.
   at GTA.Native.Function.ObjectFromNative(Type type, UInt64* value)
   at GTA.Native.Function.ReturnValueFromNativeIfNotNull[T](UInt64* result)
   at GTA.Native.Function.Call[T](Hash hash, InputArgument argument0, InputArgument argument1, InputArgument argument2)
   at LemonUI.Scaleform.InstructionalButton..ctor(String description, Control control)
   at LemonUI.Menus.NativeMenu..ctor(String bqnnerText, String name, String description, I2Dimensional banner)
   at LemonUI.Menu1.Basics..cctor()
   --- End of inner exception stack trace ---
   at LemonUI.Menu1.Basics..ctor()
[14:26:33] [ERROR] Failed to instantiate script J.AnimationMenu because constructor threw an exception: System.MissingMethodException: Method not found: 'UInt32 SHVDN.NativeMemory.GetHashKey(System.String)'.
   at GTA.Game.GenerateHash(String input)
   at GTA.Model.op_Implicit(String source)
   at J.AnimationMenu.AddAnimations()
   at J.AnimationMenu..ctor()
[14:26:33] [ERROR] Failed to instantiate script Peds.Menu1.PedsMenu because constructor threw an exception: System.TypeInitializationException: The type initializer for 'Peds.Menu1.PedsMenu' threw an exception. ---> System.MissingMethodException: Method not found: 'System.String SHVDN.NativeMemory.PtrToStringUTF8(IntPtr)'.
   at GTA.Native.Function.ObjectFromNative(Type type, UInt64* value)
   at GTA.Native.Function.ReturnValueFromNativeIfNotNull[T](UInt64* result)
   at GTA.Native.Function.Call[T](Hash hash, InputArgument argument0, InputArgument argument1, InputArgument argument2)
   at LemonUI.Scaleform.InstructionalButton..ctor(String description, Control control)
   at LemonUI.Menus.NativeMenu..ctor(String bqnnerText, String name, String description, I2Dimensional banner)
   at LemonUI.Menus.NativeMenu..ctor(String bqnnerText, String name, String description)
   at Peds.Menu1.PedsMenu..cctor()
   --- End of inner exception stack trace ---
   at Peds.Menu1.PedsMenu..ctor()

### Steps To Reproduce

Launch game, watch scripts crash

### The Current Behavior

Launch game, watch scripts crash

### The Expected Behavior

Launch game, watch scripts crash

**Comment by kagikn** [comment]
No support as you're using an asi and scripting dlls from different builds. Update all the asi and dlls all together as the reader says. You would want to update the ini and place the 3 pdb files, too. The readme says;
https://github.com/scripthookvdotnet/scripthookvdotnet/blob/ddae3cadb9d30c6d4adb430d0b08f3c0b788336f/README.md?plain=1#L38-L41

I know you're using a `ScriptHookVDotNet3.dll` from an older build than your asi file because the stacktrace didn't say `GTA.Native.Function.ReturnValueFromResultAddress` in `GTA.Native.Function.ReturnValueFromNativeIfNotNull[T](UInt64* result)`, which exist in at least between nightly.89 and nightly.106 but doesn't exist in the stable version v3.6.0.

**Comment by kagikn** [comment]
Also, please state a commit or a build version you're using when you create a bug report, not just say like "latest nightly build", because if some people see the issue later, they would get confused and wonder which version the bug report is focuses on.

**Comment by AliciaWindsor** [comment]
I never asked for your support and don't treat me like a moron. I know how to unzip files and drop them in the root folder. I passed on an issue and if you want to be in denial, so be it.

**Comment by kagikn** [comment]
This bug report is not considered valid because it doesn't follow one of the prerequisites where all the asi and the dlls must be from the same version. Don't bother creating bug reports if you don't want to follow some of the prerequisites to be considered valid, because such bug reports won't give any useful info to fix bugs because of wrong usages.

**Comment by AliciaWindsor** [comment]
I checked the asi, and indeed it was a different version. Not sure how that happened but I apologize, my mistake. I never intended to mix and match versions, it was an honest error. Again, I'm sorry. Do have a question for you, I've been scripting for years and have never installed any pdb files with SHVDN or any other scripts. Why would you consider then a requirement?

**Comment by kagikn** [comment]
Matching versions of the asi and the scripting dlls is required for bug reports because the dlls directly use some of the functions and some of the structs of the asi, and using dlls from versions different from that of the asi *may* fail to function something in the dlls (may not happen, but still wrong usage).
For your information, the 3 pdb files were added so we can diagnose issues easier in some commit after v3.6.0 was published. You should put ones into the main folder from the same version as those of the asi and the dlls, at least when you create bug reports so we can diagnose easier.
