### ISSUE TITLE
Failing to load my scripts i installed

### ISSUE THREAD

**Issue by jokezandgamez** [scripthookvdotnet/scripthookvdotnet#807]
Heres my logs

[20:18:46] [DEBUG] Created script domain 'ScriptDomain_B3914828' with v2.10.6.
[20:18:46] [DEBUG] Loading scripts from 'E:\Program Files\Rockstar Games\Grand Theft Auto V\scripts' into script domain 'ScriptDomain_B3914828' ...
[20:18:46] [INFO] Loading assembly 'FirefighterMod.dll' ...
[20:18:46] [DEBUG] Found 1 script(s) in 'FirefighterMod.dll'.
[20:18:46] [DEBUG] Starting 1 script(s) ...
[20:18:46] [DEBUG] Instantiating script 'ScripttutorialUK' in script domain 'ScriptDomain_B3914828' ...
[20:18:47] [ERROR] Failed to instantiate script 'ScripttutorialUK' because constructor threw an exception:
System.IO.FileNotFoundException: Could not load file or assembly 'NativeUI, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'NativeUI, Version=1.7.0.0, Culture=neutral, PublicKeyToken=null'
   at ScripttutorialUK.MainMenu()
   at ScripttutorialUK..ctor()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by justalemon** [comment]
Ehm, did you take the time to read?
```
Could not load file or assembly 'NativeUI
```

**Comment by Bondar1535** [comment]
Hi, everyone. That helped me:
Just copy files from the [Release.zip](https://github.com/Guad/NativeUI/releases) to your /scripts where your scripts are stored, not to main folder.

![image](https://github.com/scripthookvdotnet/scripthookvdotnet/assets/143486181/53fbb9b5-3539-430c-9ddc-70a1cda634a3)
![image](https://github.com/scripthookvdotnet/scripthookvdotnet/assets/143486181/fc094471-5f45-4363-a9a0-a7272687c39c)
